MeuDioSeries.Web/Models/ErrorViewModel.cs
using System;

namespace MeuDioSeries.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MeuDioSeries.Web/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MeuDioSeries.Web.Models
{
    public class UsuarioViewModel
    {
        [Required(ErrorMessage = "Preencha o campo Usuário")]
        [Display(Name = "Usuário")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Preencha o campo Senha")]
        [MinLength(3, ErrorMessage = "Senha precisa ter, no mínimo, 3 caracteres")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [Display(Name = "Lembrar-me")]
        public bool LembrarMe { get; set; }
    }
}

MeuDioSeries.Web/Controllers/ContaController.cs
using MeuDioSeries.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MeuDioSeries.Web.Controllers
{
    public class ContaController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UsuarioViewModel usuario)
        {
            if(usuario.Email.Equals("luan.admin@email.com") && usuario.Senha.Equals("adminLuan123"))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.Email),
                    new Claim(ClaimTypes.Email, usuario.Email),
                    new Claim(ClaimTypes.Role, "Admin")
                };

                var identity = new ClaimsIdentity(claims, "CookieSeries");
                var claimPrincipal = new ClaimsPrincipal(identity);

                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = usuario.LembrarMe
                };

                await HttpContext.SignInAsync("CookieSeries", claimPrincipal, authProperties);

                return RedirectToAction("Index", "Home");
            }
            else if (usuario.Email.Equals("luan.visitante@email.com") && usuario.Senha.Equals("visitanteLuan123"))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.Email),
                    new Claim(ClaimTypes.Email, usuario.Email),
                    new Claim(ClaimTypes.Role, "Visitante")
                };

                var identity = new ClaimsIdentity(claims, "CookieSeries");
                var claimPrincipal = new ClaimsPrincipal(identity);

                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = usuario.LembrarMe
                };

                await HttpContext.SignInAsync("CookieSeries", claimPrincipal, authProperties);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login Inválido");
            }

            return View(usuario);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("CookieSeries");

            return RedirectToAction("Index", "Home");
        }

        public IActionResult AcessoNegado()
        {
            return View();
        }
    }
}

MeuDioSeries.Web/Controllers/HomeController.cs
using MeuDioSeries.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace MeuDioSeries.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MeuDioSeries.Web/Controllers/SerieController.cs
using MeuDioSeries.Dominio.Entidades;
using MeuDioSeries.Dominio.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MeuDioSeries.Web.Controllers
{
    [Authorize]
    public class SerieController : Controller
    {
        private readonly ISerieService _serieService;
        private readonly IGeneroService _generoService;

        public SerieController(ISerieService serieService, IGeneroService generoService)
        {
            _serieService = serieService;
            _generoService = generoService;
        }

        // GET: SerieController
        [HttpGet]
        public async Task<ActionResult> Index(string title = null)
        {
            ViewData["BuscarSeries"] = title;

            IEnumerable<SerieViewModel> series;

            if (!string.IsNullOrEmpty(title))
            {
                series = await _serieService.GetSeriesByTitleAsync(title);

                return View(series);
            }
            else
            {
                series = await _serieService.GetAllAsync();

                return View(series);
            }
        }

        // GET: SerieController/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var serieViewModel = await _serieService.GetByIdAsync(id);
            return View(serieViewModel);
        }

        // GET: SerieController/Create
        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ViewBag.GeneroId = new SelectList( await _generoService.GetAllAsync(), "GeneroId", "Nome");
            return View();
        }

        // POST: SerieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SerieViewModel serieViewModel)
        {
            if (ModelState.IsValid)
            {
                await _serieService.AddAsync(serieViewModel);
                return RedirectToAction("Index");
            }

            ViewBag.GeneroId = new SelectList(await _generoService.GetAllAsync(), "GeneroId", "Nome", serieViewModel.GeneroId);
            return View(serieViewModel);
        }

        // GET: SerieController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int id)
        {
            var serieViewModel = await _serieService.GetByIdAsync(id);

            ViewBag.GeneroId = new SelectList(await _generoService.GetAllAsync(), "GeneroId", "Nome", serieViewModel.GeneroId);
            
            return View(serieViewModel);
        }

        // POST: SerieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(SerieViewModel serieViewModel)
        {
            if (ModelState.IsValid)
            {
                await _serieService.UpdateAsync(serieViewModel);
                return RedirectToAction("Index");
            }

            ViewBag.GeneroId = new SelectList(await _generoService.GetAllAsync(), "GeneroId", "Nome", serieViewModel.GeneroId);
            return View(serieViewModel);
        }

        // GET: SerieController/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            var serieViewModel = await _serieService.GetByIdAsync(id);
            return View(serieViewModel);
        }

        // POST: SerieController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var serieViewModel = await _serieService.GetByIdAsync(id);
            await _serieService.RemoveAsync(serieViewModel);

            return RedirectToAction("Index");
        }
    }
}

MeuDioSeries.Web/Views/Conta/AcessoNegado.cshtml
<div class="text-center">
    <h1 class="display-4">Ops! Acesso Negado</h1>
    <p>Parece que você não possui as credenciais para acessar esta página!</p>
</div>

MeuDioSeries.Web/Views/Conta/Login.cshtml
@model MeuDioSeries.Web.Models.UsuarioViewModel

<div class="container border" style="margin:auto; width:500px">
    <form method="post" asp-action="Login" asp-controller="Conta" class="needs-validation" novalidate style="padding: 5px">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" type="email" class="form-control" placeholder="Digite seu E-mail aqui..." minlength="5" required/>
            <div class="invalid-feedback">Por favor, digite um E-mail válido</div>
        </div>
        <div class="form-group">
            <label asp-for="Senha"></label>
            <input asp-for="Senha" type="password" class="form-control" placeholder="Digite sua Senha aqui..." minlength="3" required/>
            <span asp-validation-for="Senha" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <input asp-for="LembrarMe" type="checkbox" class="form-check-input" />
            <label asp-for="LembrarMe" class="form-check-label"></label>
        </div>
        <button type="submit" class="btn btn-success">Entrar</button>
    </form>
</div>

<script>
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

@section Scripts{ 
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeuDioSeries.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "MeuDioSeries";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo ao Meu DIO Series</h1>
    <p>Para acessar a página com as séries cadastradas, clique no link Lista de Séries. Ele está presente na barra de navegação superior.</p>
    <p>A partir da listagem, você poderá Adicionar, Atualizar, Visualizar e Excluir séries.</p>
</div>

MeuDioSeries.Web/Views/Serie/Create.cshtml
@model MeuDioSeries.Dominio.Entidades.SerieViewModel

@{
    ViewBag.Title = "Nova Série";
}

<h1>Nova Série</h1>

<h4>Série</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                @Html.DropDownList("GeneroId", ViewBag.GeneroId as SelectList,"Selecione um Gênero", new { @class="form-control"})
                @Html.ValidationMessageFor(model => model.GeneroId, "Selecione um dos Gêneros na Lista", new { @class="text-danger"} )
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Voltar à Listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeuDioSeries.Web/Views/Serie/Delete.cshtml
@model MeuDioSeries.Dominio.Entidades.SerieViewModel

@{
    ViewData["Title"] = "Exluir";
}

<h1>Excluir Série</h1>

<h3>Tem certeza que deseja EXCLUIR esta série?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a class="btn btn-secondary" asp-action="Index">Voltar à Listagem</a>
    </form>
</div>

MeuDioSeries.Web/Views/Serie/Details.cshtml
@model MeuDioSeries.Dominio.Entidades.SerieViewModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Série</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerieId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerieId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nome)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Atualizar", "Edit", new { id = Model.SerieId }, new { @class = "btn btn-primary" }) |
    <a class="btn btn-secondary" asp-action="Index">Voltar à Listagem</a>
</div>

MeuDioSeries.Web/Views/Serie/Edit.cshtml
@model MeuDioSeries.Dominio.Entidades.SerieViewModel

@{
    ViewData["Title"] = "Atualizar";
}

<h1>Atualizar</h1>

<h4>Série</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="SerieId" type="hidden" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                @Html.DropDownList("GeneroId", ViewBag.GeneroId as SelectList, String.Empty, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroId, "Selecione um dos Gêneros na Lista", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Voltar à Listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeuDioSeries.Web/Views/Serie/Index.cshtml
@model IEnumerable<MeuDioSeries.Dominio.Entidades.SerieViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Séries</h1>

<p>
    <a class="btn btn-success" asp-action="Create">Nova Série</a>
</p>

<form class="form-inline" asp-action="Index" method="get">
    <input class="form-control mb-2 mr-sm-2" type="text" placeholder="Digite um Título..." value="@ViewData["BuscarSeries"]" name="title" style="width:350px" />
    <div class="mb-2 mr-sm-2">
        <button type="submit" class="btn btn-outline-dark">Buscar</button>
    </div>
    <div class="mb-2 mr-sm-2">
        <a asp-action="Index" asp-controller="Serie">Listagem Completa</a>
    </div>
</form>

<table class="table col-md-auto">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SerieId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnoLancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SerieId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoLancamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.Nome)
            </td>
            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id=item.SerieId }, new { @class="btn btn-primary"})
                @Html.ActionLink("Visualizar", "Details", new { id=item.SerieId }, new { @class="btn btn-secondary"})
                @Html.ActionLink("Excluir", "Delete", new { id=item.SerieId }, new { @class="btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

MeuDioSeries.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meu Dio Series</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand"  style="color:white" asp-area="" asp-controller="Home" asp-action="Index">Meu Dio Series</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Serie" asp-action="Index">Lista de Séries</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="mr-2">
                <partial name="_PartialLogin" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MeuDioSeries.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MeuDioSeries.Web/Views/Shared/_PartialLogin.cshtml
@if (User.Identity.IsAuthenticated)
{
    <form method="post" class="form-check form-inline"  style="color:white" asp-action="Logout" asp-controller="Conta">
            Seja Bem-Vindo(a) @User.Identity.Name
        <button type="submit" class="ml-5 btn btn-link" style="color:white">Logout</button>
    </form>
}
else
{ 
    <a class="btn btn-link" style="color: white" asp-action="Login" asp-controller="Conta">Login</a>
}